name: Deploy Flutter Web to Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Flutter pub get
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web --release

    - name: Copy build output to deployment directory
      run: |
        rm -rf ../pages
        mkdir ../pages
        cp -r build/web/* ../pages/

    - name: Checkout pages branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan pages

    - name: Remove existing files in pages branch
      run: |
        git rm -rf .
        cp -r ../pages/* .

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Deploy Flutter web to GitHub Pages"
        git push origin pages --force
